# permissions for end users to view clustersecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustersecret-viewer-role
rules:
- apiGroups:
  - ops.k8ops.cn
  resources:
  - clustersecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ops.k8ops.cn
  resources:
  - clustersecrets/status
  verbs:
  - get
